#!/usr/bin/env python3
"""
Generate a Decodium .decodium certificate file compatible with DecodiumCertificate.

Usage:
  python3 tools/generate_cert.py 9H1SR FREE 2026-12-31
  python3 tools/generate_cert.py 9H1SR PRO  2027-12-31 --output /path/9H1SR.decodium
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import hmac
import pathlib
import sys


SIGNING_KEY = b"D3c0d1um_R4pt0r_2026_IU8LMC_s1gn_k3y_v01"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Decodium verified-station certificate."
    )
    parser.add_argument("callsign", help="Operator callsign")
    parser.add_argument("tier", choices=("FREE", "PRO"), help="Certificate tier")
    parser.add_argument(
        "expires",
        help="Expiration date in YYYY-MM-DD format",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output path; defaults to ./CALLSIGN.decodium",
    )
    return parser.parse_args()


def validate_date(date_text: str) -> str:
    try:
        dt.date.fromisoformat(date_text)
    except ValueError as exc:
        raise SystemExit(f"Invalid expires date '{date_text}': expected YYYY-MM-DD") from exc
    return date_text


def generate_signature(callsign: str, tier: str, expires: str) -> str:
    payload = f"{callsign}|{tier}|{expires}".encode("utf-8")
    return hmac.new(SIGNING_KEY, payload, hashlib.sha256).hexdigest()


def render_certificate(callsign: str, tier: str, expires: str, signature: str) -> str:
    return (
        "DECODIUM-CERT-V1\n"
        "# Decodium verified-station certificate\n"
        "# Generated by tools/generate_cert.py\n"
        f"CALL={callsign}\n"
        f"TIER={tier}\n"
        f"EXPIRES={expires}\n"
        f"SIG={signature}\n"
    )


def main() -> int:
    args = parse_args()

    callsign = args.callsign.strip().upper()
    if not callsign:
        raise SystemExit("Callsign must not be empty")

    tier = args.tier.strip().upper()
    expires = validate_date(args.expires.strip())
    signature = generate_signature(callsign, tier, expires)

    output = pathlib.Path(args.output) if args.output else pathlib.Path(f"{callsign}.decodium")
    certificate_text = render_certificate(callsign, tier, expires, signature)
    output.write_text(certificate_text, encoding="utf-8")

    print(f"Generated: {output}")
    print(f"  Call:    {callsign}")
    print(f"  Tier:    {tier}")
    print(f"  Expires: {expires}")
    print(f"  Sig:     {signature}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
